### ISSUE TITLE
Issue with the install volume binding.

### ISSUE THREAD

**Issue by Lapin** [a1ex4/ownfoil#101]
I had an issue running the 

`docker run -d -p 8465:8465 -v /games:/games /config:/app/config --name ownfoil a1ex4/ownfoil` 

line on installation saying that 
`docker: invalid reference format.
See 'docker run --help'.`

I've asked chatgpt to learn what's happening and it told me that I should fix the volume binding

`Volume Binding:
You need to use the -v flag for each volume you want to mount. In your original command, /config:/app/config is not preceded by -v, which is likely causing the issue.`

and gave me this code which worked for me.

`docker run -d -p 8465:8465 -v /games:/games -v /config:/app/config --name ownfoil a1ex4/ownfoil`

just wanted to update and help you all :) As a note, I've created /games and /config folders, gave them 777 permission and running ubuntu.

**Comment by a1ex4** [comment]
Thank you! My bad I don't ever use `docker run`... Glad you got it working.
