### ISSUE TITLE
No "New Games" section

### ISSUE THREAD

**Issue by Golumpa** [a1ex4/ownfoil#104]
Hey, new to my own shop as I have gotten fed up with shops not existing anymore and when there is some they are terribly outdated with no updates. So I decided to host my own private one for myself and some friends and family.

Currently when using OwnFoil I am able to browse the server within the file explorer but that shows everything all Titles, DLCs and Updates in a single list, which is not very intuitive. What are the chances of getting a New Games section so I am easily able to see by a game by game basis of what is on the server with icons, etc.

I am aware that TinShop has this ability but the TitleDB that uses is horribly out of date and it has no WebUI like OwnFoil to easily track updates, DLC etc.

**Comment by a1ex4** [comment]
Can you confirm your files do not include `[APP_ID][vVERSION]` in their filenames? If so you can try the `develop` tag, where there are fixes from #103 that could resolve your issue.

**Comment by Golumpa** [comment]
Hey, thanks for the update, so I did some more testing as my files were definitely named right and it would seem something to do with the reverse proxy and issue #26 so i will continue this there.
