### ISSUE TITLE
Problems in the installation Using Python [SOLVED]

### ISSUE THREAD

**Issue by juniornff** [a1ex4/ownfoil#117]
I'm using:
OS: Debian GNU/Linux 12 (bookworm) x86_64
DE: GNOME 43.9

This is more of an explanation of how I solved the problems when trying to install and use the program, to document it in case someone needs it in the future.

This is all the guide tells you so far:
```
$ git clone --recurse-submodules https://github.com/a1ex4/ownfoil
$ cd ownfoil
$ pip install -r requirements.txt
$ python app/app.py
```

Although it mentions that `pip` is used, not necessarily the one following the guide has it installed.

Then, when running `$ pip install -r requirements.txt`, the message reported in [#90](https://github.com/a1ex4/ownfoil/issues/90) appears, although the solution given was to add the `--break-system-packages` argument, but I consider that to be too abrupt to simply run a web server. For that, the same error message recommends the creation of a virtual environment, but that requires the installation of the virtual environment management package.

So I consider these two commands as Prerequisites:
```
$ sudo apt install python3-pip -y
$ sudo apt-get install python3-venv
```

And now, these would be the commands:
```
$ git clone --recurse-submodules https://github.com/a1ex4/ownfoil
$ cd ownfoil
# Create the virtual environment
$ python3 -m venv venv/
# Activate the virtual environment
$ source venv/bin/activate
$ pip install -r requirements.txt
$ python app/app.py
```
So every time i go to start the app:
```
$ cd path/to/ownfoil
$ source venv/bin/activate && python3 app/app.py && deactivate
```

When closing the app with Ctrl + C, the `deactivate` command exit the virtual environment

I leave the issue open for comments/feedback. Close it if you wish.

**Comment by a1ex4** [comment]
Thanks for the detailed instructions, although this is standard Python environment usage, so I don't want to fill the docs with these external steps.
Glad you could make it work, I'm sure it will help others too 👍
