### ISSUE TITLE
Unraid image fails to run

### ISSUE THREAD

**Issue by exolon** [a1ex4/ownfoil#138]
Can anyone shed some light? Container starts running, then shuts down. Logs show this:

> Traceback (most recent call last):
>   File "/app/app.py", line 387, in <module>
>     init()
>   File "/app/app.py", line 33, in init
>     reload_conf()
>   File "/app/app.py", line 353, in reload_conf
>     watcher.add_directory(dir)
>   File "/app/file_watcher.py", line 61, in add_directory
>     task = self.observer.schedule(self.event_handler, directory, recursive=True)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/api.py", line 306, in schedule
>     emitter.start()
>   File "/usr/local/lib/python3.11/site-packages/watchdog/utils/__init__.py", line 86, in start
>     self.on_thread_start()
>   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify.py", line 123, in on_thread_start
>     self._inotify = InotifyBuffer(path, self.watch.is_recursive, event_mask)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
>     self._inotify = Inotify(path, recursive, event_mask)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify_c.py", line 173, in __init__
>     self._add_dir_watch(path, recursive, event_mask)
>   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify_c.py", line 374, in _add_dir_watch
>     self._add_watch(full_path, mask)
>   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify_c.py", line 387, in _add_watch
>     Inotify._raise_error()
>   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify_c.py", line 404, in _raise_error
>     raise OSError(err, os.strerror(err))
> FileNotFoundError: [Errno 2] No such file or directory
> Traceback (most recent call last):
>   File "/app/app.py", line 387, in <module>
>     init()
>   File "/app/app.py", line 33, in init
>     reload_conf()
>   File "/app/app.py", line 353, in reload_conf
>     watcher.add_directory(dir)
>   File "/app/file_watcher.py", line 61, in add_directory
>     task = self.observer.schedule(self.event_handler, directory, recursive=True)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/api.py", line 306, in schedule
>     emitter.start()
>   File "/usr/local/lib/python3.11/site-packages/watchdog/utils/__init__.py", line 86, in start
>     self.on_thread_start()
>   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify.py", line 123, in on_thread_start
>     self._inotify = InotifyBuffer(path, self.watch.is_recursive, event_mask)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
>     self._inotify = Inotify(path, recursive, event_mask)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify_c.py", line 173, in __init__
>     self._add_dir_watch(path, recursive, event_mask)
>   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify_c.py", line 374, in _add_dir_watch
>     self._add_watch(full_path, mask)
>   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify_c.py", line 387, in _add_watch
>     Inotify._raise_error()
>   File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify_c.py", line 404, in _raise_error
>     raise OSError(err, os.strerror(err))
> FileNotFoundError: [Errno 2] No such file or directory
> users:x:100:games
> Starting ownfoil
> [2024-10-29 09:02:48.102] INFO (app) Starting initialization of Ownfoil...
> [2024-10-29 09:02:48.102] INFO (app) Initializing File Watcher...
> [2024-10-29 09:02:48.102] INFO (app) Loading initial configuration...
> [2024-10-29 09:02:48.102] DEBUG (settings) Reading configuration file.
> [2024-10-29 09:02:48.103] DEBUG (settings) Keys file /app/config/keys.txt does not exist.
> [2024-10-29 09:02:48.103] INFO (file_watcher) Adding directory /games to watchdog.
> [2024-10-29 09:02:48.104] INFO (file_watcher) Adding directory / to watchdog.
> users:x:100:games,ownfoil
> ownfoil:x:99:100:Linux User,,,:/home/ownfoil:/sbin/nologin
> Starting ownfoil
> [2024-10-29 09:03:11.367] INFO (app) Starting initialization of Ownfoil...
> [2024-10-29 09:03:11.367] INFO (app) Initializing File Watcher...
> [2024-10-29 09:03:11.367] INFO (app) Loading initial configuration...
> [2024-10-29 09:03:11.367] DEBUG (settings) Reading configuration file.
> [2024-10-29 09:03:11.368] DEBUG (settings) Keys file /app/config/keys.txt does not exist.
> [2024-10-29 09:03:11.368] INFO (file_watcher) Adding directory /games to watchdog.
> [2024-10-29 09:03:11.369] INFO (file_watcher) Adding directory / to watchdog.

If I start it again I get only the last part:

Starting ownfoil

> [2024-10-29 09:08:54.450] INFO (app) Starting initialization of Ownfoil...
> [2024-10-29 09:08:54.450] INFO (app) Initializing File Watcher...
> [2024-10-29 09:08:54.451] INFO (app) Loading initial configuration...
> [2024-10-29 09:08:54.451] DEBUG (settings) Reading configuration file.
> [2024-10-29 09:08:54.453] DEBUG (settings) Keys file /app/config/keys.txt does not exist.
> [2024-10-29 09:08:54.453] INFO (file_watcher) Adding directory /games to watchdog.
> [2024-10-29 09:08:54.453] INFO (file_watcher) Adding directory / to watchdog.

...and then shuts down again.
Any ideas?

**Comment by a1ex4** [comment]
The issue is with your configuration, the root directory of your server (`/`) should definitely not be configured as a directory for games for Ownfoil.

**Comment by exolon** [comment]
> The issue is with your configuration, the root directory of your server (`/`) should definitely not be configured as a directory for games for Ownfoil.

Thanks for your reply. I haven't added the container root or the NAS root as a games directory in my config - here's the docker run:

docker run
```
  -d
  --name='ownfoil'
  --net='bridge'
  --pids-limit 2048
  -e TZ="Europe/Athens"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="CPC6128"
  -e HOST_CONTAINERNAME="ownfoil"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8465]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/type0dev/Unraid-Template/main/ownfoil/icon.png'
  -p '8465:8465/tcp'
  -v '/mnt/disk1/Public/Switch/games/':'/games':'rw'
  -v '/mnt/user/appdata/ownfoil/config':'/app/config':'rw' 'a1ex4/ownfoil'
725197f9fca478cbe52379d454cc5eef8badb258eaf2c1d51dc2d06cedd82102
```
That said indeed the root path is included, so I guess there's a mistake with the container config?

```
library:
  paths:
  - /games
  - /
shop:
  clientCertKey: '-----BEGIN PRIVATE KEY-----'
  clientCertPub: '-----BEGIN PUBLIC KEY-----'
  encrypt: false
  motd: Welcome to your own shop!
  public: false
titles:
  language: en
  region: US
  valid_keys: false
```
So I removed the path and indeed it now works... thanks for the pointer!

**Comment by a1ex4** [comment]
Glad you got it to work!
