### ISSUE TITLE
save_manager: Lost connection

### ISSUE THREAD

**Issue by shumatejr** [a1ex4/ownfoil#14]
The save manager successfully grabs one save from the switch and then loses connection and fails to grab saves for the other titles.

2023-02-22 10:18:42,655 - INFO save_manager: Successfully connected to Switch device on host 192.168.86.93.
2023-02-22 10:18:42,655 - INFO save_manager: Retrieving saves from /switch/tinfoil/saves to /games/Saves/Tinfoil
2023-02-22 10:18:42,749 - INFO save_manager: Scanning /switch/tinfoil/saves/
2023-02-22 10:18:42,860 - INFO save_manager: Lost connection, attempting reconnect in 10s...

**Comment by a1ex4** [comment]
And then you don't have anymore logs, it doesn't try to reconnect ?

I think sys-light-ftp is pretty fragile when it comes to retrieving large files, that's the reconnect mechanism is in place. Despite trying for a few minutes I cannot reproduce your issue.

**Comment by shumatejr** [comment]
I believe I narrowed down the problem to folder permissions. It was trying to write a file where it didn't have the rights and it logs it as a connection issue. Updated permissions on the server with chmod and it appears to be working now.

**Comment by COIh0rp** [comment]
@shumatejr can you elaborate on what you did to solve this? I am having the same issue. I've tried modifying permissions with no success. I'm using a 2 tb external drive. It is able to be accessed by the switch OK, but when it backs up a save it only does the first one then looses connection as you describe. I've also tried this on both linux and windows setups with both ntfs and ext4 file systems with the same result

**Comment by shumatejr** [comment]
> @shumatejr can you elaborate on what you did to solve this? I am having the same issue. I've tried modifying permissions with no success. I'm using a 2 tb external drive. It is able to be accessed by the switch OK, but when it backs up a save it only does the first one then looses connection as you describe. I've also tried this on both linux and windows setups with both ntfs and ext4 file systems with the same result

I did chmod 777 on all the directories that are accessed just to make sure there were no permissions issues.
