### ISSUE TITLE
Tinfoil wont detect half of Games/DLC

### ISSUE THREAD

**Issue by nooblolerxd** [a1ex4/ownfoil#143]
the website is fine, it shows the games, all the dlc. but then when i open tinfoil. it doesnt show anything. (Super smash bros dlc and other games)

**Comment by nooblolerxd** [comment]
nvm i found the problem (didnt dumb the keys)

**Comment by Goldenwolfz21** [comment]
> nvm i found the problem (didnt dumb the keys)

wdm by dumb the keys im having the same issue

**Comment by a1ex4** [comment]
It means dumping you console keys to a file and then importing the file in Ownfoil, see the guide: https://gitlab.com/easyhacking/switch/-/wikis/home/getting-started/dump-keys
