### ISSUE TITLE
docker wont start.

### ISSUE THREAD

**Issue by nooblolerxd** [a1ex4/ownfoil#145]
when i open my server the http website doesnt work. it worked when i originally downloaded it. but after i closed the server and reopened it it doesnt work
i downloaded it from docker

**Comment by FoUStep** [comment]
It works fine here, so must be in your setup. If you want help, you'll need to give more information, logs and errors.

**Comment by a1ex4** [comment]
@FoUStep feel free to reopen if you are still having issues.
