### ISSUE TITLE
not an issue, just a observation which may help people with their config

### ISSUE THREAD

**Issue by brendongl** [a1ex4/ownfoil#155]
So i was having lots of unraid issues with overloading ram/cpu.
Ownfoil doesnt like games within sub-directories.

I had some folders with pack/game folder/game.
Ive removed the packs and it seems to have scanned and loaded everything (with prod keys) fine.
Fingers crossed it stays that way.

**Comment by a1ex4** [comment]
Thanks for the info, that's weird because I can definitely see it working in the structure with subfolders, we'll continue the Unraid discussion in #111...
