### ISSUE TITLE
More Permission Issues

### ISSUE THREAD

**Issue by Dark98** [a1ex4/ownfoil#17]
docker logs ownfoil

Creating group app with GID 1000
Creating user app with UID 1000
Setting up authentification for user dark.
Adding password for user dark
Starting ownfoil
2023-03-09 06:48:57,702 - INFO apscheduler.scheduler: Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-03-09 06:48:57,706 - INFO apscheduler.scheduler: Added job "Generate shop" to job store "default"
2023-03-09 06:48:57,706 - INFO apscheduler.scheduler: Scheduler started
2023-03-09 06:48:57,707 - INFO apscheduler.executors.default: Running job "Generate shop (trigger: interval[0:05:00], next run at: 2023-03-09 06:48:57 UTC)" (scheduled at 2023-03-09 06:48:57.587910+00:00)
2023-03-09 06:48:57,711 - INFO gen_shop: Found 0 directories, 3 game/save files
2023-03-09 06:48:57,711 - ERROR gen_shop: Failed to write /games/shop.json, error was:
[Errno 13] Permission denied: '/games/shop.json'
2023-03-09 06:48:57,712 - ERROR gen_shop: Failed to write /games/shop.tfl, error was:
[Errno 13] Permission denied: '/games/shop.tfl'
2023-03-09 06:48:57,712 - INFO apscheduler.executors.default: Job "Generate shop (trigger: interval[0:05:00], next run at: 2023-03-09 06:53:57 UTC)" executed successfully

**Comment by littleferris** [comment]
I am getting this exact same issue, did you figure it out or can anyone else help? 

`
2023/07/27 08:24:37 | stderr | 2023-07-27 15:24:37,947 - INFO apscheduler.executors.default: Job "Backup saves (trigger: interval[1:00:00], next run at: 2023-07-27 16:22:30 UTC)" executed successfully
-- | -- | --
2023/07/27 08:24:37 | stderr | 2023-07-27 15:24:37,947 - INFO save_manager: Device 192.168.1.200 is unavailable, aborting.
2023/07/27 08:22:30 | stderr | 2023-07-27 15:22:30,620 - INFO apscheduler.executors.default: Job "Generate shop (trigger: interval[0:05:00], next run at: 2023-07-27 15:27:30 UTC)" executed successfully
2023/07/27 08:22:30 | stderr | [Errno 13] Permission denied: '/games/shop.tfl'
2023/07/27 08:22:30 | stderr | 2023-07-27 15:22:30,620 - ERROR gen_shop: Failed to write /games/shop.tfl, error was:
2023/07/27 08:22:30 | stderr | [Errno 13] Permission denied: '/games/shop.json'
2023/07/27 08:22:30 | stderr | 2023-07-27 15:22:30,620 - ERROR gen_shop: Failed to write /games/shop.json, error was:
2023/07/27 08:22:30 | stderr | 2023-07-27 15:22:30,620 - INFO gen_shop: Found 8 directories, 0 game/save files
2023/07/27 08:22:30 | stderr | 2023-07-27 15:22:30,616 - INFO apscheduler.executors.default: Running job "Backup saves (trigger: interval[1:00:00], next run at: 2023-07-27 15:22:30 UTC)" (scheduled at 2023-07-27 15:22:30.612088+00:00)
2023/07/27 08:22:30 | stderr | 2023-07-27 15:22:30,616 - INFO apscheduler.executors.default: Running job "Generate shop (trigger: interval[0:05:00], next run at: 2023-07-27 15:22:30 UTC)" (scheduled at 2023-07-27 15:22:30.497260+00:00)
2023/07/27 08:22:30 | stderr | 2023-07-27 15:22:30,615 - INFO apscheduler.scheduler: Scheduler started
2023/07/27 08:22:30 | stderr | 2023-07-27 15:22:30,615 - INFO apscheduler.scheduler: Added job "Backup saves" to job store "default"
2023/07/27 08:22:30 | stderr | 2023-07-27 15:22:30,615 - INFO apscheduler.scheduler: Added job "Generate shop" to job store "default"
2023/07/27 08:22:30 | stderr | 2023-07-27 15:22:30,612 - INFO apscheduler.scheduler: Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023/07/27 08:22:30 | stderr | 2023-07-27 15:22:30,611 - INFO apscheduler.scheduler: Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023/07/27 08:22:29 | stdout | Starting ownfoil


</body>
</html>`

**Comment by Dark98** [comment]
Unfortunately I didn't :( I opted for smb instead

**Comment by littleferris** [comment]
I figured it out on mine. I had to manually add permissions for the folders and now it works great!

**Comment by a1ex4** [comment]
Fixed in the rewrite of Ownfoil where permission issues is no longer a thing, see #43.
