### ISSUE TITLE
container does not create the contents of nginx folder once volume mount it

### ISSUE THREAD

**Issue by BohemianGecko** [a1ex4/ownfoil#2]
When mounting nginx folder to follow the setup authentication instructions, no files are created inside that folder, and instead the container exits with this error:
`nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)`

**Comment by TuRDMaN** [comment]
Same with the /app folder. I had to copy the contents manually from within the container.

**Comment by haudankaivajasi** [comment]
> Same with the /app folder. I had to copy the contents manually from within the container.

How did you achieve this?

**Comment by reddragond** [comment]
@haudankaivajasi create the container with the bind mounts pointing to different folders. I used ./app:/app2 and ./nginx:/etc/nginx2

Then you can run `docker exec ownfoil cp -r /app/* /app2 && cp -r /etc/nginx/* /etc/nginx2`
After that you stop the container and relaunch it with the correct bind mounts

**Comment by a1ex4** [comment]
Hey, indeed the way to configure the nginx basic auth was less than ideal.

I released a new version where this has completely been rewritten to make it more straightforward, please see the new documentation for the 1.1.0 version.
