### ISSUE TITLE
Empty filenames

### ISSUE THREAD

**Issue by xeeeeeeeee** [a1ex4/ownfoil#20]
Hi,
I have my switch library organized by folders, when I access the shop all my games filenames are empty.
Also, If I open a random game, it just opens a html page for that game. 

Something like this, If I open the empty filename of game1 or game2 it just displays the html page.
Game3 that is in the root dir shows with the correct filename and opens fine.
/games/:
- shop_config.toml
- shop_template.toml
- game1/game1.nsp
- game2/game2.nsp
- game3.nsp

Is this a known issue?
Any fix possible?
Thanks

**Comment by Dark98** [comment]
> Hi,
> I have my switch library organized by folders, when I access the shop all my games filenames are empty.
> Also, If I open a random game, it just opens a html page for that game. 
> 
> Something like this, If I open the empty filename of game1 or game2 it just displays the html page.
> Game3 that is in the root dir shows with the correct filename and opens fine.
> /games/:
> - shop_config.toml
> - shop_template.toml
> - game1/game1.nsp
> - game2/game2.nsp
> - game3.nsp
> 
> Is this a known issue?
> Any fix possible?
> Thanks

I don't use ownfoil due to my own issues with it, but try renaming the .nsps to "Game Name [Title ID].nsp"

**Comment by fcmonteiro** [comment]
Yes, the file names already follow that format.

**Comment by blasirio** [comment]
@xeeeeeeeee the shop.json looks something like this?

    "files": [
        {
            "url": "../Pokemon XXXXXXXXXX.nsp",
            "size": 795493252
        },
        
        If so it should work.
