### ISSUE TITLE
index.html error

### ISSUE THREAD

**Issue by jdoe29103** [a1ex4/ownfoil#3]
2023/01/11 18:06:46 [error] 9#9: *11 "/games/index.html" is not found (2: No such file or directory)

I keep getting this message in my logs whenever I try and connect from tinfoil. I have no idea what index.html even is.

**Comment by a1ex4** [comment]
Hi, I've never seen this error with Ownfoil and Tinfoil, the app isn't supposed to be looking for an `index.html` file.

I released a new version of Ownfoil, can you test it out and report back if your issue is still present?

**Comment by a1ex4** [comment]
I'll close this issue with the lack of info, feel free to reopen if you encouter it again.

**Comment by jdoe29103** [comment]
@a1ex4 I have tried to new version and I have the same issue as before. Here is my compose file:

version: "3"

services:
  ownfoil:
    container_name: ownfoil
    image: a1ex4/ownfoil
    environment:
      # For write permission in /games directory
      - PUID=1000
      - PGID=100
      # Setup auth
      - USERNAME=a1ex
      - PASSWORD=pass
      # - ROOT_DIR=/games
      # - SAVE_ENABLED=true
    volumes:
      - /srv/mergerfs/pool/games/Console/Nintendo Switch:/games
    ports:
      - "8110:80"
