### ISSUE TITLE
Permission denied for shop_config.toml

### ISSUE THREAD

**Issue by SubGplayz** [a1ex4/ownfoil#30]
![image](https://github.com/a1ex4/ownfoil/assets/68687751/1a7d2975-c317-4782-a679-1f4aee83c798)

whenever I try and use this on my synology nas, it always gives me this error. It works when I use it on my PC, so im not sure what im doing wrong.

**Comment by Seruschl** [comment]
I inserted the UID and GID from my User on my synology NAS and it worked for me.

Login on your NAS via SSH with your user and then look it up with the id command.

**Comment by a1ex4** [comment]
Fixed in the rewrite of Ownfoil where permission issues is no longer a thing, see #43.
