### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by SiscuPrats** [a1ex4/ownfoil#44]
Not initialize, Console error:

sudo: unknown user python
sudo: error initializing audit plugin sudoers_audit

**Comment by LokeYourC3PH** [comment]
I am having the same issue. Did you figure it out @SiscuPrats ?

**Comment by a1ex4** [comment]
I recommend you switch to the `v2` branch as this issue should never happen and I won't look into fixing errors on the original code, so much more features and fixes are in v2.
Feel free to reopen if you still have the issue, but it shouldn't happen anymore.
