### ISSUE TITLE
ownfoil:v2 Unable to read json file

### ISSUE THREAD

**Issue by shoyrock** [a1ex4/ownfoil#54]
I updated to version 2 that came out yesterday, but I'm now getting this erroI was was working fine on the older version 2
_________________________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "/app/app.py", line 174, in <module>
    init()
  File "/app/app.py", line 15, in init
    update_titledb(app_settings)
  File "/app/titles.py", line 173, in update_titledb
    load_titledb(app_settings)
  File "/app/titles.py", line 82, in load_titledb
    cnmts_db = json.load(f)
               ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1115346 column 14 (char 37282819)
warning: The following paths are not up to date and were left despite sparse patterns:
        US.en.json

After fixing the above paths, you may want to run `git sparse-checkout reapply`.
Traceback (most recent call last):
  File "/app/app.py", line 174, in <module>
    init()
  File "/app/app.py", line 15, in init
    update_titledb(app_settings)
  File "/app/titles.py", line 173, in update_titledb
    load_titledb(app_settings)
  File "/app/titles.py", line 82, in load_titledb
    cnmts_db = json.load(f)
               ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1115346 column 14 (char 37282819)
warning: The following paths are not up to date and were left despite sparse patterns:
        US.en.json

After fixing the above paths, you may want to run `git sparse-checkout reapply`.
Traceback (most recent call last):
  File "/app/app.py", line 174, in <module>
    init()
  File "/app/app.py", line 15, in init
    update_titledb(app_settings)
  File "/app/titles.py", line 173, in update_titledb
    load_titledb(app_settings)
  File "/app/titles.py", line 82, in load_titledb
    cnmts_db = json.load(f)
               ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1115346 column 14 (char 37282819)
users:x:100:games
Starting ownfoil
users:x:100:games,ownfoil
ownfoil:x:99:100:Linux User,,,:/home/ownfoil:/sbin/nologin
Starting ownfoil
reading conf file
users:x:100:games,ownfoil
ownfoil:x:99:100:Linux User,,,:/home/ownfoil:/sbin/nologin
Starting ownfoil
reading conf file

**Comment by a1ex4** [comment]
To identify every games Ownfoil uses the database from Tinfoil, which gets updated periodically by the creator by scraping the Nintendo e-shop. But sometimes files are updated with errors and so that breaks Ownfoil too, I opened an issue on the repository to see if we can prevent that from happening in the future (blawar/titledb#28).

In the meantime, in Ownfoil the database is updated every start of the app (it will be updated periodically in the future), so you need to wait for the database to be fixed upstream and then a restart of the container should grab the latest update.

Also make sure to pull the latest image, I should have fixed the git sparse-checkout issues with the latest commits.

**Comment by acaltas** [comment]
have the same with latest image of V2

> Starting ownfoil
> 
> Traceback (most recent call last):
> 
>   File "/app/app.py", line 174, in <module>
> 
>     init()
> 
>   File "/app/app.py", line 15, in init
> 
>     update_titledb(app_settings)
> 
>   File "/app/titles.py", line 173, in update_titledb
> 
>     load_titledb(app_settings)
> 
>   File "/app/titles.py", line 82, in load_titledb
> 
>     cnmts_db = json.load(f)
> 
>                ^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
> 
> reading conf file
> 
>     return loads(fp.read(),
> 
>            ^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
> 
>     return _default_decoder.decode(s)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
> 
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> 
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
> 
>     obj, end = self.scan_once(s, idx)
> 
>                ^^^^^^^^^^^^^^^^^^^^^^
> 
> json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1115346 column 14 (char 37282819)

**Comment by SiscuPrats** [comment]
I also verify that I have the same problem with the latest version.



Starting ownfoil
Traceback (most recent call last):
  File "/app/app.py", line 174, in <module>
    init()
  File "/app/app.py", line 15, in init
    update_titledb(app_settings)
  File "/app/titles.py", line 173, in update_titledb
    load_titledb(app_settings)
  File "/app/titles.py", line 82, in load_titledb
    cnmts_db = json.load(f)
               ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1115346 column 14 (char 37282819)

**Comment by a1ex4** [comment]
Fixed upstream by blawar, restarting Ownfoil should fix it locally.

**Comment by shoyrock** [comment]
Nice, I was able to get the container running but now I’m running into another error
![image](https://github.com/a1ex4/ownfoil/assets/51036435/1138c0da-c1f8-4f7f-8fd4-68dc4e69e3e5)

**Comment by acaltas** [comment]
check the container log.. mabybe its indexing everything

**Comment by a1ex4** [comment]
@shoyrock maybe you ran the app twice ? I would suggest stopping the container, removing the ./config/ownfoil.db file (you'll lose the users registered but the library will be indexed again) and restarting the container.

**Comment by YozenPL** [comment]
I removed the .db, created new container, tried to start it few time but all I'm getting is:

```
ownfoil:x:1000:ownfoil
ownfoil:x:1000:1000:Linux User,,,:/home/ownfoil:/sbin/nologin
Starting ownfoil
warning: The following paths are not up to date and were left despite sparse patterns:
        US.en.json

After fixing the above paths, you may want to run `git sparse-checkout reapply`.
```
