### ISSUE TITLE
No games visible, only the two .toml files?

### ISSUE THREAD

**Issue by FrankEBailey** [a1ex4/ownfoil#56]
I'm running the Ownfoil container in Docker Desktop on Win10 with WSL2. The container runs and if I visit the localhost:8000 url in my browser or in Tinfoil, I only see the two .toml files, and there are no games in "New Games" on the left in Tinfoil. Clearly I've done something wrong, but if anyone might know what that _something_ is, I'd appreciate any help you can offer.

**Comment by a1ex4** [comment]
It's probably because the folder you mounted to /games in the container is not the correct one. You need to specify it correctly in the Dockerfile.

**Comment by FrankEBailey** [comment]
so like, my games folder is on my A: drive, so I used /mnt/a/nintendo switch/games - which is the format I use when referring to any windows folder inside wsl2, does it need to be in a different format?

**Comment by migm16** [comment]
i have same issue, \Nas\Switch\Switch Games\"name of game in this" folder. i found that if i take the file out of the folder and place it in \Switch Games\ folder i can see it in tinfoil under well nsp's show up in new games section, um what i would like is to be able to keep all the games and there updates/dlc in there folder but still have them show up in new games is this possible

**Comment by Sollozzo38** [comment]
i have a folder named "games" in the folder "ownfoil-develop", where i put the nsp's in...
i start the container with the compose.yml where is volumes "/games".
when i connect via tinfoil i only see the two .toml-files - where i have to put the games in or how i have to change the volume?

**Comment by MMeldrum** [comment]
@migm16 have you checked the logs for the ownfoil instance that shuts down immediately? I also run this on a RPi4 and I think I had that problem initially too.
