### ISSUE TITLE
Ownfoil GUI vs Tinfoil

### ISSUE THREAD

**Issue by Sev7nrayne** [a1ex4/ownfoil#57]
Currently on V2.

Here is my docker compose

version: "3"

services:
  ownfoil:
    container_name: ownfoil
    image: a1ex4/ownfoil:v2
    environment:
      # For write permission in /games directory
      - PUID=1000
      - PGID=100
      # Setup auth
      - USERNAME=admin
      - PASSWORD=admin
      - ROOT_DIR=/games
      - SAVE_ENABLED=true
    volumes:
      - /volume1/docker/ownfoil/config:/app/config
      - /volume1/docker/ownfoil/games:/games
    ports:
      - "8465:8465"

Game Folder:
![image](https://github.com/a1ex4/ownfoil/assets/134185750/69023a41-9c71-4021-a569-49464d1996f2) 
4 games total (base)

Ownfoil Gui:
![image](https://github.com/a1ex4/ownfoil/assets/134185750/09e9f41e-9388-4b22-aeee-915a029af4f6)
3 games showing
How to correct this?

Tinfoil (16.0):
Shows XCI on the left w/ only 2 game files displaying
SMBW.xci
MGSMC.xci

I do not see the .nsz or .nsp in Tinfoil - but I can search and find them. 
They are just not showing up on its on .nsz or .nsp tab (left)
How to correct this? 

Feature request:
Is there a way to populate tabs for each .extension or be able to create a tab in the config folder that shows all games within the /games directory

**Comment by a1ex4** [comment]
There is nothing for me to fix here. The MGSMC Title Id is missing from titledb, so the game won't show up in the UI until this is fixed (in [blawar/titledb](https://github.com/blawar/titledb)). Does the game show up normal in Tinfoil on your Switch?

For the tabs I don't think there is supposed to be a "nsp" or "nsz" tab, only XCI is a separate tab, the games are found under the "New games" tab.

**Comment by Sev7nrayne** [comment]
"There is nothing for me to fix here. The MGSMC Title Id is missing from titledb,"
Understood, thank you.

"Does the game show up normal in Tinfoil on your Switch?"
e.i. RDR [01007820196A6000][v0].nsz (base) shows up in the GUI but does not show in [New Games] but I can search for it and it comes up available to be installed

**Comment by Sev7nrayne** [comment]
I found where my mistake was for missing games, but still searchable.
There is no v0 for this game on tinfoil's db search. 
Removed the [v0] and now it shows in tinfoil [New Games].

Naming convention is important [Title][Title id][Version]

Hopefully there will be an up-2-date tool that can rename files based on a db record search like: [switch-library-manager](https://github.com/gregoo/switch-library-manager) - last updated 2021 (doesn't work well in finding some games)

Thank you @a1ex4 for Ownfoil.
Looks like I have no further issues or concerns at this time.

**Comment by Sev7nrayne** [comment]
Bug: Red Dead Redemption 01007820196A6000 shows in the Ownfoil GUI but not in Tinfoil.
It is searchable and the update does show in [New Updates]
I originally had a .nsz and then downloaded .nsp version to test - same outcome
I have another .nsz file that does show in both interfaces {Borderlands The Pre-Sequel Ultimate Edition [010007400FF24000].nsz}

**Comment by Sev7nrayne** [comment]
log: New file to add: /games/Red Dead Redemption/Red Dead Redemption [01007820196A6000][v1].nsz
Unable to identify file dkbt.xci, app ID: None. The error was: 'NoneType' object has no attribute 'lower'

**Comment by Sev7nrayne** [comment]
Following up on v2 tests: https://github.com/a1ex4/ownfoil/discussions/52
