### ISSUE TITLE
V2 ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by CodeHedge** [a1ex4/ownfoil#58]
I can run v1 no problem. When i switch my compose to the :v2, i cant see the webpage and get error
![image](https://github.com/a1ex4/ownfoil/assets/35341367/789daf34-608f-45f5-adc2-1ed3daf466b9)

Heres my file
![image](https://github.com/a1ex4/ownfoil/assets/35341367/60b5b2e6-c268-4113-b277-c967fad58912)

**Comment by a1ex4** [comment]
As specified in the v2 tracking issue, use port 8465.
