### ISSUE TITLE
HTTPS / SSL native configuration

### ISSUE THREAD

**Issue by FoUStep** [a1ex4/ownfoil#64]
Feature request:
Could you possibly make the docker(-compose) with options for HTTPS/SSL with a configuration towards a certificate and port?

I don't like reverse proxy's. I would rather prefer it to be directly into the docker image.

**Comment by FoUStep** [comment]
Not sure if there are parameters which can change the nginx.conf? Make 80 into 443 with a snake-oil certificate or self signed.

Does Tinfoil verify the SSL certificate? Perhaps it is my lack of understanding of running it in docker to be able to change the internal configuration.

**Comment by a1ex4** [comment]
It is not the goal of the project to handle ssl certificates, you should use an external tool to generate the certificates and handling the routing from domain name to Ownfoil.

On the v2 branch it should be straightforward and easy to expose the endpoint.
