### ISSUE TITLE
[FEAT] Multiple user authentication

### ISSUE THREAD

**Issue by chrisdma** [a1ex4/ownfoil#7]
Hello,

Does ownfoil support multiple username/passwords in the env variables for multiple users to setup authentication with?

**Comment by a1ex4** [comment]
Currently a single user is supported. I added your feature request to the project's roadmap.

**Comment by chrisdma** [comment]
Awesome mate, that would be pretty sweet if this could be added. Appreciate your time in making this. 

Can you also possibly change the shop file from re-scanning/generating every 5 minutes to on every tinfoil http request? This way it will be constsntly updated as needed?

**Comment by a1ex4** [comment]
I'm also looking into adding authentication using keys, will see if this can be something simple for the user to do.

> Can you also possibly change the shop file from re-scanning/generating every 5 minutes to on every tinfoil http request? This way it will be constsntly updated as needed?

Yeah, this will be one of the first things implemented when I switch from nginx to something like Flask.

**Comment by a1ex4** [comment]
Implemented in the rewrite of Ownfoil, see #43.
