### ISSUE TITLE
Prod.keys doesn't work

### ISSUE THREAD

**Issue by Filippo-Galli** [a1ex4/ownfoil#70]
Hi, 
I'm running ownfoil v2 using docker-compose without problems but when I try to upload prod.keys from the website everything crashes and I can't reach the site anymore. The only way to reach again the shop is to stop the container, delete the folder config and run again the container. 
### Step to reproduce
From the settings page of the site I upload my prod.keys

**Comment by Sev7nrayne** [comment]
@Fili-ai are you still facing this issue?
Also if the GUI crashes you still can get to the settings by adding /settings to the end of the URL string.
U can use keys from here to test:
https://prodkeys.co/yuzu-prod-keys/

**Comment by Fili-ai** [comment]
Yes, the step to reproduce my error is the following: 
- open settings; 
- load the prod.keys in the correct form; 
- submit the key and the site display the green text "Keys are valid";
- click on "Library" and the site starts to load but nothing happens. 

After a while of loading the screen became white and showed me this: 
![20231115_17h09m30s_grim](https://github.com/a1ex4/ownfoil/assets/59925664/6de1b7f2-ceb5-490c-a6c2-866a95c6bf22)
![20231115_17h09m46s_grim](https://github.com/a1ex4/ownfoil/assets/59925664/f1365ded-1444-45e4-af8f-3c53b325998e)

If I try to refresh the page it shows the white screen attached before. 
If I turn off the docker container, delete the config folder and restart the container it work but I can't see all of my games.

**Comment by Sev7nrayne** [comment]
@Fili-ai you are not alone,
This is currently still an issue we are facing
See: https://github.com/a1ex4/ownfoil/discussions/52
Waiting for the OP to resolve.

In the meantime the shop still works in the background only the GUI is not populating.
You can still proceed with setting up your shop in tinfoil to install games.

**Comment by Fili-ai** [comment]
Thanks, sorry I didn't see that issue.
Unfortunately I still don’t see all my games in the tinfoil shop. However, the shop.json file is populated with all the games in my directory. I thought it was a prod.keys problem but even with the shop background it persists.

**Comment by Sev7nrayne** [comment]
@Fili-ai 
Make sure the naming convention for all files follow name[titleid][version]

.nsp will show up in [New Games]
.xci will show up in [XCI]
Xci is a cartridge dump and nsp are eshop files*

Titles are cross checked here when it is loaded into the DB: https://github.com/blawar/titledb

You can search here for correct titleid, versions, dlc, builds: https://tinfoil.io/Title/

**Comment by a1ex4** [comment]
Should be fixed by latest commit.

**Comment by Fili-ai** [comment]
Thanks, I try it now.
