### ISSUE TITLE
Docker just breaks windows

### ISSUE THREAD

**Issue by WrttenSkate522** [a1ex4/ownfoil#74]
I went to install docker, and when it's down installing it tells me to restart. So I clicked restart now, but when my computer started up it couldn't boot into the OS, and the recovery screen comes up. After a bunch of fiddling, I got my my computer working again, but I deleted everything related to docker. So how can I use this if I can't install docker?

**Comment by HenryBaby** [comment]
Seems like an issue that has nothing to do with this project. You'll find more help if you look here: https://docs.docker.com/desktop/install/windows-install/
