### ISSUE TITLE
just wanted to say tank you

### ISSUE THREAD

**Issue by gamingoninsulin** [a1ex4/ownfoil#75]
hello a1ex4,

i wanted to say i set this up realy easy today and even made a template for this today

here take a look 

[ownfoil-template.json](https://github.com/a1ex4/ownfoil/files/13796631/ownfoil-template.json)
you may use it if your want ;)

greeting gamingoninsulin

**Comment by a1ex4** [comment]
Thanks, glad you find it useful!
