### ISSUE TITLE
/games/index.html is not found

### ISSUE THREAD

**Issue by mrkrauz123** [a1ex4/ownfoil#76]
Hello I just did a clean install of ownfoil on docker. The whole log when starting and trying to connect to the shop is shown in the following:

> 2024/01/05 01:16:51 [error] 27#27: *1 "/games/index.html" is not found (2: No such file or directory), client: 192.168.8.143, server: , request: "GET / HTTP/1.1", host: "192.168.8.223:8001"
> Adding password for user abcxyz
> Creating group app with GID 1000
> 2024-01-05 01:18:19,251 - INFO apscheduler.executors.default: Job "Backup saves (trigger: interval[1:00:00], next run at: 2024-01-05 02:16:08 UTC)" executed successfully
> 2024-01-05 01:16:08,705 - INFO apscheduler.scheduler: Adding job tentatively -- it will be properly scheduled when the scheduler starts
> Creating user app with UID 1000
> Setting up authentification for user abcxyz.
> Starting ownfoil
> 2024-01-05 01:16:08,704 - INFO apscheduler.scheduler: Adding job tentatively -- it will be properly scheduled when the scheduler starts
> 2024-01-05 01:16:08,706 - INFO apscheduler.scheduler: Added job "Generate shop" to job store "default"
> 2024-01-05 01:16:08,706 - INFO apscheduler.scheduler: Added job "Backup saves" to job store "default"
> 2024-01-05 01:16:08,706 - INFO apscheduler.scheduler: Scheduler started
> 2024-01-05 01:16:08,707 - INFO apscheduler.executors.default: Running job "Generate shop (trigger: interval[0:05:00], next run at: 2024-01-05 01:16:08 UTC)" (scheduled at 2024-01-05 01:16:08.704452+00:00)
> 2024-01-05 01:16:08,707 - INFO apscheduler.executors.default: Running job "Backup saves (trigger: interval[1:00:00], next run at: 2024-01-05 01:16:08 UTC)" (scheduled at 2024-01-05 01:16:08.704922+00:00)
> 2024-01-05 01:16:08,724 - INFO gen_shop: Found 146 directories, 190 game/save files
> 2024-01-05 01:16:08,726 - INFO gen_shop: Successfully wrote /games/shop.json
> 2024-01-05 01:16:08,728 - INFO gen_shop: Successfully wrote /games/shop.tfl
> 2024-01-05 01:16:08,728 - INFO apscheduler.executors.default: Job "Generate shop (trigger: interval[0:05:00], next run at: 2024-01-05 01:21:08 UTC)" executed successfully
> 192.168.8.143 - abcxyz [05/Jan/2024:01:16:51 +0000] "GET / HTTP/1.1" 404 146 "-" "-" "-"
> 2024-01-05 01:18:19,250 - INFO save_manager: Device 192.168.1.200 is unavailable, aborting.

All of my files are picked up and stored inside of shop.json but I cannot connect to the shop for the life of me. I have reread the instructions over and over again and I cannot figure out what I missed. Thanks in advance.

**Comment by C8kilc8ac** [comment]
I am having a very similar problem. Started a separate issue.

**Comment by Jamdoog** [comment]
I can replicate this issue when deploying. I assume it's to do with custom user and group ID's being passed to the container.

NGINX cannot read the contents of /games. 

Manually setting permissions will enable access for NGINX (e.g. chmod 777 /games).

I don't have time to contribute a fix right now but if someone would like to resolve the permission issue, here is the fault.

Thanks

**Comment by a1ex4** [comment]
I recommend you switch to the `v2` branch as this issue should never happen and I won't look into fixing errors on the original code, so much more features and fixes are in v2.
