### ISSUE TITLE
[V2] Problem with requirements

### ISSUE THREAD

**Issue by rage1337** [a1ex4/ownfoil#82]
Hi,

after updating the image, an error regarding the imports pops up:

`Traceback (most recent call last):`
`  File "/app/app.py", line 10, in <module>`
`    from titles import *`
`  File "/app/titles.py", line 7, in <module>`
`    import requests`
`ModuleNotFoundError: No module named 'requests'`

**Comment by haudankaivajasi** [comment]
Getting the same error here

**Comment by a1ex4** [comment]
Should be fixed with latest commit, you can try the latest image

**Comment by rage1337** [comment]
Merci, works again. Thank you for all your efforts!
